Library/Library/Models/Books.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Library.Models
{
    public class Books
    {
        [Required]
        [Display(Name = "Book ID")]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Book Name")]
        [StringLength(100)]
        public string bookName { get; set; }

        [Display(Name = "Genre")]
        public Genres genre { get; set; }

        [Required]
        [Display(Name = "Genre ID")]
        public int genreID { get; set; }

        [Display(Name = "Date Added")]
        public DateTime dateAdded { get; set; }

        [Display(Name = "Release Date")]
        public DateTime releaseDate { get; set; }

        [Display(Name = "Author")]
        [StringLength(150)]
        public string author { get; set; }
        
        [Display(Name = "Membership Type")]
        public int membershipType { get; set; }

        [Display(Name = "Summary")]
        [StringLength(500)]
        public string summary { get; set; }
     
    }

}

Library/Library/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library.Models;
using Library.ViewModel;


namespace Library.Controllers
{
    public class BooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Books
        public ActionResult Index()
        {
            var infoBook = db.Books.Join(
                                        db.MembershipTypes,
                                        r => r.membershipType,
                                        m => m.ID,
                                        (r, m) => new InfoBookViewModel{
                                        genre = r.genre.genreName,
                                        book = r.bookName,
                                        ID = r.ID,
                                        dateAdded =r.dateAdded,
                                        releaseDate =r.releaseDate,
                                        author= r.author,
                                        summary = r.summary,
                                        membershipType =m.membershipType });

            if (User.IsInRole("Manager"))
                return View("Index",infoBook.ToList());
            else
                return View("ReadOnlyIndex", infoBook.ToList());  
        }

        // GET: Books/BooksByGenre/1
        public ActionResult BooksByGenre(int? genreID)
        {
            var books = db.Books.Include(m => m.genre);
            IEnumerable<Books> query = books;
            query = books.Where(m => m.genreID == genreID);

            var infoBook = query.Join(
                                        db.MembershipTypes,
                                        r => r.membershipType,
                                        m => m.ID,
                                        (r, m) => new InfoBookViewModel
                                        {
                                            genre = r.genre.genreName,
                                            book = r.bookName,
                                            ID = r.ID,
                                            dateAdded = r.dateAdded,
                                            releaseDate = r.releaseDate,
                                            author= r.author,
                                            summary = r.summary,
                                            membershipType = m.membershipType
                                        });
            if (User.IsInRole("Manager"))
                return View("Index", infoBook.ToList());
            else
                return View("ReadOnlyIndex", infoBook.ToList());

        }

        [HttpPost]
        public ActionResult Search(string genreID, string membershipTypeID, string date)
        {
            int queryParams = 0;
            int membershipCheck;
            int genreCheck;
            DateTime dateCheck;

            if (Int32.TryParse(membershipTypeID, out membershipCheck))
            {
                if (membershipCheck > 0)
                    queryParams += 1;
            }
            if (Int32.TryParse(genreID, out genreCheck))
            {
                if (genreCheck > 0)
                    queryParams += 2;
            }
            if (DateTime.TryParse(date, out dateCheck)){
                queryParams += 4;
            }

            var books = db.Books.Include(m => m.genre);
            IEnumerable<Books> query = books;

            switch (queryParams)
            {
                case 1:
                    query = books.Where(m => m.membershipType == membershipCheck);
                    break;
                case 2:
                    query = books.Where(m => m.genreID == genreCheck);
                    break;
                case 3:
                    query = books.Where(m => m.membershipType == membershipCheck && m.genreID == genreCheck);
                    break;
                case 4:
                    query = books.Where(m => m.releaseDate > dateCheck);
                    break;
                case 5:
                    query = books.Where(m => m.membershipType == membershipCheck && m.releaseDate > dateCheck);
                    break;
                case 6:
                    query = books.Where(m => m.genreID == genreCheck && m.releaseDate > dateCheck);
                    break;
                case 7:
                    query = books.Where(m => m.membershipType == membershipCheck && m.genreID == genreCheck && m.releaseDate > dateCheck);
                    break;
                default:
                    query = books;
                    break;
            }

            //var books = db.Books.Include(m => m.genre);
            //return View(books.ToList());
            var infoBook = query.Join(
                                        db.MembershipTypes,
                                        r => r.membershipType,
                                        m => m.ID,
                                        (r, m) => new InfoBookViewModel
                                        {
                                            genre = r.genre.genreName,
                                            book = r.bookName,
                                            ID = r.ID,
                                            dateAdded = r.dateAdded,
                                            releaseDate = r.releaseDate,
                                            author= r.author,
                                            summary = r.summary,
                                            membershipType = m.membershipType
                                        });
            if (User.IsInRole("Manager"))
                return View("Index", infoBook.ToList());
            else
                return View("ReadOnlyIndex", infoBook.ToList());
        }


        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }


        // GET: Books/Create
        [Authorize(Roles = "Manager")]
        public ActionResult Create()
        {
            ViewBag.genreID = new SelectList(db.Genres, "ID", "ID");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public ActionResult Create([Bind(Include = "ID,genreID,Name,dateAdded,releaseDate,author,summary, membershipType")] Books books)
        {

            if (ModelState.IsValid)
            {
                if (books.dateAdded < books.releaseDate || books.dateAdded > DateTime.Today || books.releaseDate > DateTime.Today )
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    db.Books.Add(books);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.genreID = new SelectList(db.Genres, "ID", "ID", books.genreID);
            return View(books);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.genreID = new SelectList(db.Genres, "ID", "ID", books.genreID);
            return View(books);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public ActionResult Edit([Bind(Include = "ID,genreID,bookName,dateAdded,releaseDate,author,summary,membershipType")] Books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.genreID = new SelectList(db.Genres, "ID", "ID", books.genreID);
            return View(books);
        }

        // GET: Books/Delete/5
        [Authorize(Roles = "Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Books books = db.Books.Find(id);
            db.Books.Remove(books);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Manager")]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

Library/Library/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Models;
using System.Data.Entity;
using System.Collections;
using Library.ViewModel;
using System.Data;

namespace Library.Controllers
{
    public class RentalsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Rentals
        
        public ActionResult Index()
        {
            var user = User.Identity.Name;

            var rentals = db.Rentals.Where(m => m.rentalExpiration >= DateTime.Today);

            if (User.IsInRole("Manager"))
            {
                //IEnumerable<Rentals> groupByRentals = rentals.GroupBy(rentals,user);
                var rentalsGenre = rentals.Join(db.Books, r => r.rentalBook, m => m.bookName, (r,m) => new RentalViewModel {book = r.rentalBook, genre = m.genre.genreName, rentalUser = r.rentalUser , rentalExpiration = r.rentalExpiration});       
                return View("Index", rentalsGenre.ToList());
            }
            else
            {
                IEnumerable<Rentals> userRentals = rentals.Where(m => m.rentalUser == user);
                return View("ReadOnlyIndex", userRentals.ToList());
            }
        }
        public ActionResult IndexAll()
        {
            var user = User.Identity.Name;
            var rentals = db.Rentals;

            if (User.IsInRole("Manager"))
            {
                var rentalsGenre = rentals.Join(db.Books, r => r.rentalBook, m => m.bookName, (r, m) => new RentalViewModel { book = r.rentalBook, genre = m.genre.genreName, rentalUser = r.rentalUser, rentalExpiration = r.rentalExpiration });
                return View("Index", rentalsGenre.ToList());
            }

            else { 
            IEnumerable<Rentals> userAllRentals = rentals.Where(m => m.rentalUser == user);
            return View("ReadOnlyIndex", userAllRentals.ToList());
            }

        }

        [Authorize (Roles = "Manager")]
        public ActionResult GroupBy1()
        {
            var rentals = db.Rentals;
            var rentalsGenre = rentals.Join(db.Books, r => r.rentalBook, m => m.bookName, (r, m) => new RentalViewModel { book = r.rentalBook, genre = m.genre.genreName, rentalUser = r.rentalUser, rentalExpiration = r.rentalExpiration });
            
            return View("GroupByUser", rentalsGenre.ToList());
           
        }

        [Authorize(Roles = "Manager")]
        public ActionResult GroupBy2()
        {
            var rentals = db.Rentals;
            var rentalsGenre = rentals.Join(db.Books, r => r.rentalBook, m => m.bookName, (r, m) => new RentalViewModel { book = r.rentalBook, genre = m.genre.genreName, rentalUser = r.rentalUser, rentalExpiration = r.rentalExpiration });
            
            return View("GroupByGenres", rentalsGenre.ToList());

        }

        [HttpPost]
        public ActionResult Search(string genreID, string membershipTypeID, string date)
        {
            int queryParams = 0;
            int membershipCheck;
            int genreCheck;
            DateTime dateCheck;

            if (Int32.TryParse(membershipTypeID, out membershipCheck))
            {
                if (membershipCheck > 0)
                    queryParams += 1;
            }
            if (Int32.TryParse(genreID, out genreCheck))
            {
                if (genreCheck > 0)
                    queryParams += 2;
            }
            if (DateTime.TryParse(date, out dateCheck))
            {
                queryParams += 4;
            }

            var books = db.Books.Include(m => m.genre);
            IEnumerable<Books> booksQuery = books;
            var rentals = db.Rentals;
            IEnumerable<Rentals> rentalsQuery = rentals;

            switch (queryParams)
            {
                case 1:
                    booksQuery = books.Where(m => m.membershipType == membershipCheck);
                    break;
                case 2:
                    booksQuery = books.Where(m => m.genreID == genreCheck);
                    break;
                case 3:
                    booksQuery = books.Where(m => m.membershipType == membershipCheck && m.genreID == genreCheck);
                    break;
                case 4:
                    rentalsQuery = rentals.Where(m => m.rentalExpiration >= dateCheck);
                    break;
                case 5:
                    booksQuery = books.Where(m => m.membershipType == membershipCheck);
                    rentalsQuery = rentals.Where(m => m.rentalExpiration >= dateCheck);
                    break;
                case 6:
                    booksQuery = books.Where(m => m.genreID == genreCheck);
                    rentalsQuery = rentals.Where(m => m.rentalExpiration >= dateCheck);
                    break;
                case 7:
                    booksQuery = books.Where(m => m.membershipType == membershipCheck && m.genreID == genreCheck);
                    rentalsQuery = rentals.Where(m => m.rentalExpiration >= dateCheck);
                    break;
                default:
                    break;
            }

            var rentalsGenre = rentalsQuery.Join(booksQuery, r => r.rentalBook, m => m.bookName, (r, m) => new RentalViewModel { book = r.rentalBook, genre = m.genre.genreName, rentalUser = r.rentalUser, rentalExpiration = r.rentalExpiration });
            return View("Index", rentalsGenre.ToList());
        }

        public ActionResult Rent(string book)
        {
            var user = User.Identity.Name;
            var rentals = db.Rentals;
            IEnumerable<Rentals> userRentals = rentals.Where(m => m.rentalUser == user && m.rentalExpiration>=DateTime.Today);
            var dupCheck = false;

            foreach(Rentals rental in userRentals)
            {
                if (rental.rentalBook == book)
                    dupCheck = true;               
            }
            if (dupCheck)
            {
             return RedirectToAction("Index");

            }

            else
            {
                var rental = new Rentals
                {
                    rentalUser = User.Identity.Name,
                    rentalExpiration = DateTime.Today.AddDays(3)                                       
                };

                rental.rentalBook = book;

                db.Rentals.Add(rental);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

Library/Library/Views/Books/Create.cshtml
@model Library.Models.Books

@{
    ViewBag.Title = "Create";
}

<h2 id="pageTitle">Create New Book</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.Label("Genre ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-bottom:-1em">
                @{
                    var genres = new List<SelectListItem>();
                    genres.Add(new SelectListItem { Text = "", Value = "0" });
                    genres.Add(new SelectListItem { Text = "Comedy", Value = "1" });
                    genres.Add(new SelectListItem { Text = "Romance", Value = "2" });
                    genres.Add(new SelectListItem { Text = "Drama", Value = "3" });
                    genres.Add(new SelectListItem { Text = "Action", Value = "4" });
                    genres.Add(new SelectListItem { Text = "Horror", Value = "5" });
                    genres.Add(new SelectListItem { Text = "SciFi", Value = "6" });
                    genres.Add(new SelectListItem { Text = "Kids", Value = "7" });
                    genres.Add(new SelectListItem { Text = "Family", Value = "8" });
                    genres.Add(new SelectListItem { Text = "Biography", Value = "9" });
                    genres.Add(new SelectListItem { Text = "Adult", Value = "10" });
                    genres.Add(new SelectListItem { Text = "Thriller", Value = "11" });
                    genres.Add(new SelectListItem { Text = "Adventure", Value = "12" });
                }

                @Html.DropDownList("genreID", genres, htmlAttributes: new { @class = "form-control" }) <br />
                @Html.ValidationMessageFor(model => model.genreID, "", new { @class = "text-danger" })

            </div>
        </div>
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.bookName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bookName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bookName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.releaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.releaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.releaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.summary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Membership Type:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-bottom:-1em">
                @{
                    var types = new List<SelectListItem>();
                    types.Add(new SelectListItem { Text = "", Value = "0" });
                    types.Add(new SelectListItem { Text = "Free", Value = "1" });
                    types.Add(new SelectListItem { Text = "Premium", Value = "2" });
                }

                @Html.DropDownList("membershipType", types, htmlAttributes: new { @class = "form-control" }) <br />
                @Html.ValidationMessageFor(model => model.membershipType, "", new { @class = "text-danger" })

            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="margin-left: 21em">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
                    }

<div style="margin-left:20.8em">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Library/Library/Views/Books/Details.cshtml
@model Library.Models.Books

<link rel="stylesheet" href="~/Content/Search.css" />

@{
    ViewBag.Title = "Details";
}

<h2 id="pageTitle">@Html.DisplayFor(model => model.bookName) Details</h2>


<div>
    <dl class="dl-horizontal" id="details">
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.genreID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genreID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.bookName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bookName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.releaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.releaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.summary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.summary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.membershipType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.membershipType)
        </dd>

    </dl>

    <div style="font-size: 18px; color:#005348; margin-left: 6.5em;">
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Library/Library/Views/Books/ReadOnlyIndex.cshtml
@model IEnumerable<Library.ViewModel.InfoBookViewModel>

<!--  jQuery -->
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

<!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

<!-- Bootstrap Date-Picker Plugin -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />

<link rel="stylesheet" href="~/Content/Search.css" />

@{
    ViewBag.Title = "Books";
}

<h2 id="pageTitle">Books</h2>
<hr />

<div class="row">
    <div style="width: 40%; float:left; margin-left: 1.5em;">
        <div class="container" style="width:1800px;">
            @using (Html.BeginForm("Search", "Books"))
            {
                <p>
                    <label class="label label-primary" style="font-size:18px; margin-left: -1.2em;">Search a Book</label>
                    <div class="form-group" id="myForm" style="font-size:17px; margin-left: -2em; margin-top:20px;">
                        @Html.Label("Genre:", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10" style="margin-bottom:-1em">
                            @{
                                var genres = new List<SelectListItem>();
                                genres.Add(new SelectListItem { Text = "", Value = "0" });
                                genres.Add(new SelectListItem { Text = "Comedy", Value = "1" });
                                genres.Add(new SelectListItem { Text = "Romance", Value = "2" });
                                genres.Add(new SelectListItem { Text = "Drama", Value = "3" });
                                genres.Add(new SelectListItem { Text = "Action", Value = "4" });
                                genres.Add(new SelectListItem { Text = "Horror", Value = "5" });
                                genres.Add(new SelectListItem { Text = "SciFi", Value = "6" });
                                genres.Add(new SelectListItem { Text = "Kids", Value = "7" });
                                genres.Add(new SelectListItem { Text = "Family", Value = "8" });
                                genres.Add(new SelectListItem { Text = "Biography", Value = "9" });
                                genres.Add(new SelectListItem { Text = "Adult", Value = "10" });
                                genres.Add(new SelectListItem { Text = "Thriller", Value = "11" });
                                genres.Add(new SelectListItem { Text = "Adventure", Value = "12" });
                            }

                            @Html.DropDownList("genreID", genres, htmlAttributes: new { @class = "form-control" }) <br />
                        </div>

                        @Html.Label("Membership Type:", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10" style="margin-bottom:-1em">
                            @{
                                var types = new List<SelectListItem>();
                                types.Add(new SelectListItem { Text = "", Value = "0" });
                                types.Add(new SelectListItem { Text = "Free", Value = "1" });
                                types.Add(new SelectListItem { Text = "Premium", Value = "2" });
                            }

                            @Html.DropDownList("membershipTypeID", types, htmlAttributes: new { @class = "form-control" }) <br />
                        </div>

                        @Html.Label("Date Release:", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10" style="margin-bottom:-1em">
                            <div class="input-group date" data-provide="datepicker">
                                <input type="text" class="form-control" style="width:240px;" name="date">
                                <div class="input-group-addon" style="width:30px; margin-left: 8px">
                                    <span class="glyphicon glyphicon-th"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-6" style="margin-left:7em; margin-top:30px">
                            <button type="submit" class="btn btn-primary" style="width:100px"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                        </div>
                    </div>
                </p>
            }
        </div>
    </div>

    <div style="width: 40%; float:right; margin-left: 1.5em;">
        <label class="label label-primary" style="font-size:18px; margin-left: 6em;"> The Joy Of Books </label>
        <video id="video" style="margin-top: 10px" width="420" controls>
            <source src="~/Content/the_joy_of_books.mp4" type="video/mp4">
            Your browser does not support HTML5 video.
        </video>
    </div>
</div>

<table class="table" id="bookTable">
    <br />
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.book)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.releaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.summary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.membershipType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateAdded)
        </th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.genre)
            </td>
            <td>
                @Html.ActionLink(item.book, "Rent", "Rentals", new { book = item.book }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.releaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.summary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.membershipType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateAdded)
            </td>
        </tr>
    }

</table>